openapi: 3.0.0
info:
  title: API de Roles
  description: API para la gestión de roles y sus permisos.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local
paths:
  /roles:
    post:
      summary: Crear un nuevo rol
      description: Crea un nuevo rol y le asigna permisos.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Administrador"
                permisos:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
      responses:
        "201":
          description: Rol creado con éxito.
        "500":
          description: Error interno del servidor.
    get:
      summary: Obtener todos los roles
      description: Retorna una lista de roles con sus permisos asociados.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de roles obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    rol:
                      type: string
                      example: "Administrador"
                    permisos:
                      type: array
                      items:
                        type: string
                      example: ["crear_usuarios", "eliminar_usuarios"]
        "500":
          description: Error interno del servidor.
  /roles/{id}:
    patch:
      summary: Modificar un rol existente
      description: Actualiza el nombre y permisos de un rol.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Supervisor"
                permisos:
                  type: array
                  items:
                    type: integer
                  example: [1, 4]
      responses:
        "200":
          description: Rol actualizado correctamente.
        "404":
          description: El rol no existe.
        "500":
          description: Error interno del servidor.
    delete:
      summary: Eliminar un rol
      description: Elimina un rol y sus relaciones con permisos.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Rol eliminado correctamente.
        "404":
          description: El rol no existe.
        "500":
          description: Error interno del servidor.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
