openapi: 3.0.0
info:
  title: API de Clientes
  version: 1.0.0
  description: Endpoints para listar, registrar y actualizar clientes. Requiere autenticación JWT y verificación de permisos.

servers:
  - url: http://localhost:5000
    description: Servidor local

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: "Cliente ABC"
        estado:
          type: boolean
          example: true

security:
  - bearerAuth: []

paths:
  /clientes:
    get:
      summary: Obtener lista de clientes
      description: Retorna una lista paginada y filtrada de clientes. Requiere el permiso `ver_clientes`.
      parameters:
        - in: query
          name: pagina
          schema:
            type: integer
            example: 1
          description: Número de página a consultar.
        - in: query
          name: resultados_por_pagina
          schema:
            type: integer
            example: 10
          description: Número de clientes por página.
        - in: query
          name: nombre
          schema:
            type: string
            example: ABC
          description: Filtro por coincidencia parcial del nombre del cliente (insensible a mayúsculas).
        - in: query
          name: estado
          schema:
            type: boolean
            example: true
          description: Filtrar por estado del cliente (`true` para activos, `false` para inactivos).
      responses:
        "200":
          description: Lista de clientes obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagina:
                    type: integer
                    example: 1
                  resultados_por_pagina:
                    type: integer
                    example: 10
                  total_resultados:
                    type: integer
                    example: 25
                  total_paginas:
                    type: integer
                    example: 3
                  clientes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Cliente'
        "401":
          description: Token inválido o no enviado.
        "403":
          description: Permiso insuficiente.
        "500":
          description: Error interno del servidor.

    post:
      summary: Registrar un nuevo cliente
      description: Registra un Cliente con su nombre. Requiere el permiso `registrar_clientes`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nombre
              properties:
                nombre:
                  type: string
                  example: "Cliente XYZ"
      responses:
        "201":
          description: Cliente registrado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cliente registrado exitosamente"
                  cliente:
                    $ref: '#/components/schemas/Cliente'
        "400":
          description: El nombre del cliente es requerido.
        "401":
          description: Token inválido o no enviado.
        "403":
          description: Permiso insuficiente.
        "500":
          description: Error al registrar cliente.

  /clientes/{id}:
    patch:
      summary: Actualizar cliente
      description: Permite actualizar nombre y/o estado de un cliente. Requiere el permiso `modificar_clientes`.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del cliente a actualizar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Cliente Actualizado"
                estado:
                  type: boolean
                  example: false
      responses:
        "200":
          description: Cliente actualizado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cliente actualizado exitosamente"
                  cliente:
                    $ref: '#/components/schemas/Cliente'
        "400":
          description: No se proporcionó ningún campo para actualizar.
        "401":
          description: Token inválido o no enviado.
        "403":
          description: Permiso insuficiente.
        "404":
          description: cliente no encontrado.
        "500":
          description: Error al actualizar cliente.
